compute_precision:
  grad_scaler: False
dino:
  loss_weight: 1.0
  head_n_prototypes: 8192
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
ibot:
  loss_weight: 1.0
  separate_head: true
  head_n_prototypes: 8192
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  batch_size_per_gpu: 64
  dataset_path: /shared/eng/bpt3/data/UniViT/data/trainingDataset.pkl
  saveckp_freq: 1
  seed: 0
  num_workers: 4
  OFFICIAL_EPOCH_LENGTH: 4403
  cache_dataset: true
  centering: sinkhorn_knopp
student:
  arch: vit_base
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.999
  final_momentum_teacher: 0.999
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0
optim:
  epochs: 25
  weight_decay: 0.01
  weight_decay_end: 0.01
  base_lr: 1.0e-05
  lr: 1.0e-05
  warmup_epochs: 0
  min_lr: 1.0e-05
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: single_node
  patch_embed_lr_mult: 0.2
  layerwise_decay: 1.0
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.32
  - 1.0
  local_crops_number: 2
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224
  local_crops_size: 98
evaluation:
  eval_period_iterations: 0